### ISSUE TITLE
Add the GPL license to the repo

### ISSUE THREAD

**Issue by multimeric** [pratas/xs#3]
I'm attempting to get this published on bioconda, but it looks like the repo needs to have a copy of the license included before we can do that ([discussion here](https://github.com/bioconda/bioconda-recipes/pull/15414#discussion_r285228983)). It's also actually a requirement of the GPL that you provide the license, it seems.

**Comment by pratas** [comment]
Hi! We are very gratefull!

**Comment by pratas** [comment]
It has been updated.
